### ISSUE TITLE
更换账户后dry_run_raw swap_exact_token_for_token合约失败

### ISSUE THREAD

**Issue by renzholy** [starcoinorg/starswap-interface#26]
怀疑是没有注册代币对导致的，但是dry_run_raw register_swap_pair合约也失败

**Comment by tarvos21** [comment]
如果用户之前只有STC，没有Usdx，它需要发起一个accept-token的交易，接受`0x07fa08a855753f0ff7292fdcbe871216::Usdx::Usdx`这个token，这样swap才可能成功

**Comment by tarvos21** [comment]
有新的contract function，会自动执行accept-token:

https://github.com/starcoinorg/starswap-core/pull/3

**Comment by tarvos21** [comment]
starswap-core 增加了自动accept-token功能，新用户会无需再单独发起accept-token交易
